opc_ua_gateway:
  build: .
  environment:
    - mqtt=mqtt://127.0.0.1
    - opc_end_point=opc.tcp://DESKTOP-BMPPPBP:4334/OPCUA/SimulationServer
    - opc_node_id=ns=5;s=Counter1
    - requestedPublishingInterval=1000
